# Generated by Django 6.0.5 on 2026-05-09 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estancias', '0001_initial'),
        ('reservas', '0002_reserva_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estancia',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estancia', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='estancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='estancias.estancia'),
        ),
        migrations.AddField(
            model_name='folio',
            name='estancia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='estancias.estancia'),
        ),
    ]
