# Generated by Django 6.0.5 on 2026-05-26 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_metodos_pago(apps, schema_editor):
    MetodoPago = apps.get_model('estancias', 'MetodoPago')
    for nombre, tipo in [
        ('Efectivo', 'EFECTIVO'),
        ('Tarjeta', 'TARJETA'),
        ('Billetera digital', 'BILLETERA'),
        ('Transferencia', 'TRANSFERENCIA'),
    ]:
        MetodoPago.objects.get_or_create(nombre=nombre, defaults={'tipo': tipo, 'activo': True})


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0007_comprobante_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('BILLETERA', 'Billetera digital'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_operacion', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='APROBADO', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=180)),
                ('es_simulado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_normalizados', to='estancias.folio')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='estancias.metodopago')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='INGRESO', max_length=20)),
                ('concepto', models.CharField(choices=[('PAGO_FOLIO', 'Pago de folio'), ('ANULACION', 'Anulacion'), ('AJUSTE', 'Ajuste')], default='PAGO_FOLIO', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_operacion', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=180)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='estancias.metodopago')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_caja', to='estancias.pago')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], max_length=20)),
                ('serie', models.CharField(default='B001', max_length=10)),
                ('numero', models.PositiveIntegerField()),
                ('cliente_documento', models.CharField(max_length=20)),
                ('cliente_nombre', models.CharField(max_length=180)),
                ('cliente_direccion', models.CharField(blank=True, max_length=220)),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('ANULADO', 'Anulado'), ('PENDIENTE', 'Pendiente')], default='EMITIDO', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_emitidos', to=settings.AUTH_USER_MODEL)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='estancias.pago')),
            ],
            options={
                'ordering': ['-fecha_emision'],
                'unique_together': {('tipo', 'serie', 'numero')},
            },
        ),
        migrations.RunPython(crear_metodos_pago, migrations.RunPython.noop),
    ]
