# Generated by Django 6.0.5 on 2026-05-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0008_metodopago_pago_movimientocaja_comprobante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoFolio',
        ),
    ]
