# Generated by Django 6.0.5 on 2026-07-14 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0013_politica_cobro_unica_recomendada'),
        ('reservas', '0010_reserva_fecha_limite_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='concepto',
            field=models.CharField(choices=[('PAGO_FOLIO', 'Pago de folio'), ('ADELANTO_RESERVA', 'Adelanto de reserva'), ('ANULACION', 'Anulacion'), ('AJUSTE', 'Ajuste')], default='PAGO_FOLIO', max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_normalizados', to='estancias.folio'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('folio__isnull', False), ('reserva__isnull', False), _connector='OR'), name='pago_tiene_destino'),
        ),
    ]
