# Generated by Django 6.0.5 on 2026-07-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0014_pago_reserva_alter_movimientocaja_concepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncobro',
            name='horas_cancelacion_gratuita',
            field=models.PositiveIntegerField(default=48, help_text='Horas minimas antes del check-in para devolver el adelanto.'),
        ),
        migrations.AddField(
            model_name='configuracioncobro',
            name='porcentaje_retencion_cancelacion_tardia',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Porcentaje del adelanto que retiene el hotel por cancelacion tardia.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='concepto',
            field=models.CharField(choices=[('PAGO_FOLIO', 'Pago de folio'), ('ADELANTO_RESERVA', 'Adelanto de reserva'), ('DEVOLUCION_RESERVA', 'Devolucion de reserva'), ('ANULACION', 'Anulacion'), ('AJUSTE', 'Ajuste')], default='PAGO_FOLIO', max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='estancias.pago'),
        ),
        migrations.AddConstraint(
            model_name='configuracioncobro',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_retencion_cancelacion_tardia__gte', 0), ('porcentaje_retencion_cancelacion_tardia__lte', 100)), name='config_retencion_cancelacion_valida'),
        ),
    ]
