# Generated by Django 6.0.5 on 2026-07-16 12:09

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0015_configuracioncobro_horas_cancelacion_gratuita_and_more'),
        ('habitaciones', '0003_habitacionestadohistorial'),
        ('reservas', '0012_reservaestadohistorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoestancia',
            name='estancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='estancias.estancia'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='estancias.pago'),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='habitaciones.habitacion'),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estancia', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='estancia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='folio', to='estancias.estancia'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='estancias.pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_normalizados', to='estancias.folio'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adelantos', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='prorrogaestancia',
            name='estancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prorrogas', to='estancias.estancia'),
        ),
        migrations.AddConstraint(
            model_name='comprobante',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='comprobante_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('igv')))), name='folio_total_cuadra_subtotal_igv'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='movimiento_caja_monto_positivo'),
        ),
    ]
