# Generated by Django 6.0.5 on 2026-07-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0016_alter_cargoestancia_estancia_alter_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncobro',
            name='horas_plazo_pago_garantia',
            field=models.PositiveIntegerField(default=24, help_text='Horas disponibles para completar la garantia antes de liberar la habitacion.'),
        ),
        migrations.AddField(
            model_name='configuracioncobro',
            name='porcentaje_early_checkin',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Recargo sobre una noche por ingresar antes de la hora de check-in.', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracioncobro',
            name='porcentaje_garantia_reserva',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Porcentaje del total que debe pagarse para confirmar una reserva.', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracioncobro',
            name='porcentaje_igv',
            field=models.DecimalField(decimal_places=2, default=18, help_text='IGV incluido en las tarifas y productos del hotel.', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracioncobro',
            name='porcentaje_late_checkout',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Recargo sobre una noche por salir después de la hora de check-out.', max_digits=5),
        ),
        migrations.AddField(
            model_name='folio',
            name='porcentaje_igv',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='configuracioncobro',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_garantia_reserva__gt', 0), ('porcentaje_garantia_reserva__lte', 100)), name='config_garantia_reserva_valida'),
        ),
        migrations.AddConstraint(
            model_name='configuracioncobro',
            constraint=models.CheckConstraint(condition=models.Q(('horas_plazo_pago_garantia__gt', 0)), name='config_plazo_garantia_positivo'),
        ),
        migrations.AddConstraint(
            model_name='configuracioncobro',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_igv__gte', 0), ('porcentaje_igv__lte', 100)), name='config_igv_valido'),
        ),
        migrations.AddConstraint(
            model_name='configuracioncobro',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_early_checkin__gte', 0), ('porcentaje_early_checkin__lte', 100)), name='config_early_checkin_valido'),
        ),
        migrations.AddConstraint(
            model_name='configuracioncobro',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_late_checkout__gte', 0), ('porcentaje_late_checkout__lte', 100)), name='config_late_checkout_valido'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_igv__gte', 0), ('porcentaje_igv__lte', 100)), name='folio_porcentaje_igv_valido'),
        ),
    ]
