# Generated by Django 6.0.5 on 2026-07-16 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0017_configuracioncobro_horas_plazo_pago_garantia_and_more'),
        ('habitaciones', '0003_habitacionestadohistorial'),
        ('reservas', '0014_reserva_porcentaje_early_checkin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estancia',
            index=models.Index(fields=['habitacion', '-fecha_checkout'], name='est_hab_checkout_idx'),
        ),
        migrations.AddIndex(
            model_name='estancia',
            index=models.Index(fields=['estado', 'fecha_salida_programada'], name='est_estado_salida_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['tipo', '-fecha'], name='mov_tipo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado', '-creado_en'], name='pago_estado_fecha_idx'),
        ),
    ]
