# Generated by Django 6.0.5 on 2026-05-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('estrellas', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
