# Generated by Django 6.0.5 on 2026-07-14 04:07

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def inicializar_garantia_reservas(apps, schema_editor):
    Reserva = apps.get_model('reservas', 'Reserva')
    for reserva in Reserva.objects.all().iterator():
        reserva.porcentaje_adelanto = Decimal('50.00')
        reserva.monto_adelanto_requerido = (
            Decimal(reserva.precio_total or 0) * Decimal('0.50')
        ).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        reserva.save(update_fields=['porcentaje_adelanto', 'monto_adelanto_requerido'])


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacionestadohistorial'),
        ('hoteles', '0001_initial'),
        ('reservas', '0009_snapshot_politica_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_limite_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_adelanto_requerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='porcentaje_adelanto',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.RunPython(inicializar_garantia_reservas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_adelanto__gte', 0), ('porcentaje_adelanto__lte', 100)), name='reserva_porcentaje_adelanto_valido'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('monto_adelanto_requerido__gte', 0)), name='reserva_adelanto_no_negativo'),
        ),
    ]
