# Generated by Django 6.0.5 on 2026-07-15 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacionestadohistorial'),
        ('hoteles', '0001_initial'),
        ('reservas', '0010_reserva_fecha_limite_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='horas_cancelacion_gratuita',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_reembolsado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_retenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='reserva',
            name='porcentaje_retencion_cancelacion_tardia',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_cancelacion',
            field=models.CharField(blank=True, choices=[('', 'Sin cancelacion'), ('SIN_PAGO', 'Cancelacion sin pago'), ('GRATUITA', 'Cancelacion dentro del plazo'), ('TARDIA', 'Cancelacion tardia con retencion'), ('VENCIMIENTO_PAGO', 'Vencimiento del plazo de pago')], default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_retencion_cancelacion_tardia__gte', 0), ('porcentaje_retencion_cancelacion_tardia__lte', 100)), name='reserva_retencion_cancelacion_valida'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('monto_reembolsado__gte', 0)), name='reserva_reembolso_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('monto_retenido__gte', 0)), name='reserva_retencion_no_negativa'),
        ),
    ]
