# Generated by Django 6.0.5 on 2026-07-16 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_historial_inicial(apps, schema_editor):
    Reserva = apps.get_model('reservas', 'Reserva')
    Historial = apps.get_model('reservas', 'ReservaEstadoHistorial')
    for reserva in Reserva.objects.all().iterator():
        historial = Historial.objects.create(
            reserva_id=reserva.id,
            estado_anterior='',
            estado_nuevo=reserva.estado,
            motivo='Estado existente al habilitar el historial de reservas.',
        )
        Historial.objects.filter(pk=historial.pk).update(cambiado_en=reserva.creado_en)


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_reserva_cancelada_en_reserva_cancelada_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('CANCELADA', 'Cancelada'), ('NO_SHOW', 'No-show')], max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_reserva', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='reservas.reserva')),
            ],
            options={
                'ordering': ['-cambiado_en', '-id'],
            },
        ),
        migrations.RunPython(crear_historial_inicial, migrations.RunPython.noop),
    ]
