# Generated by Django 6.0.5 on 2026-07-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
        ('reservas', '0012_reservaestadohistorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hoteles.hotel'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='huesped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.huesped'),
        ),
        migrations.AlterField(
            model_name='reservaestadohistorial',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_estados', to='reservas.reserva'),
        ),
    ]
