# Generated by Django 6.0.5 on 2026-07-16 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacionestadohistorial'),
        ('hoteles', '0001_initial'),
        ('reservas', '0013_alter_reserva_hotel_alter_reserva_huesped_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='porcentaje_early_checkin',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='reserva',
            name='porcentaje_igv',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddField(
            model_name='reserva',
            name='porcentaje_late_checkout',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_igv__gte', 0), ('porcentaje_igv__lte', 100)), name='reserva_porcentaje_igv_valido'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_early_checkin__gte', 0), ('porcentaje_early_checkin__lte', 100)), name='reserva_early_checkin_valido'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_late_checkout__gte', 0), ('porcentaje_late_checkout__lte', 100)), name='reserva_late_checkout_valido'),
        ),
    ]
