# Generated by Django 6.0.5 on 2026-07-16 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacionestadohistorial'),
        ('hoteles', '0001_initial'),
        ('reservas', '0014_reserva_porcentaje_early_checkin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado', 'fecha_entrada', 'fecha_salida'], name='res_estado_fechas_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['-creado_en'], name='res_creado_idx'),
        ),
    ]
